import { auth, ensureAnonymousUser, watchFirebaseConnection } from './firebase.js';
import * as signaling from './signaling.js';
import { createDiagnostics, rtcConfig, wirePeer } from './webrtc.js';
const remoteVideo = document.getElementById('remote-video'); const diagnostics = createDiagnostics(document.getElementById('status'), document.getElementById('debug'), 'tv'); let room; let peer;
watchFirebaseConnection(function (connected) { diagnostics.firebase(connected); });
document.getElementById('play-video').addEventListener('click', function () { remoteVideo.play().then(function () { diagnostics.status('Reproducción activada.'); }).catch(diagnostics.error); });
async function receiveGuest(offer) { if (peer) { return; } peer = new RTCPeerConnection(rtcConfig); diagnostics.observe(peer, 'guestTv'); peer.addTransceiver('audio', { direction: 'recvonly' }); peer.addTransceiver('video', { direction: 'recvonly' }); peer.addEventListener('track', function (event) { remoteVideo.srcObject = event.streams[0]; diagnostics.remoteTrack('guestTv'); remoteVideo.play().catch(function () { diagnostics.status('Vídeo recibido. Pulsa “Activar reproducción”.'); }); }); const setRemote = wirePeer(peer, room.sessionId, 'guestTv', 'tv', 'guest', diagnostics, signaling); await setRemote(offer); await peer.setLocalDescription(await peer.createAnswer()); await signaling.writeDescription(room.sessionId, 'guestTv', 'tv', peer.localDescription); diagnostics.status('Conectando con el familiar…'); }
async function start() { try { const user = await ensureAnonymousUser(); if (!auth.currentUser || auth.currentUser.uid !== user.uid) { throw new Error('No se pudo iniciar la sesión temporal.'); } room = await signaling.createSession(user.uid); document.getElementById('pairing-code').textContent = room.code; diagnostics.status('Esperando celular de Tuto.'); signaling.watchRole(room.sessionId, 'tutoPhoneUid', function (value) { if (value) { diagnostics.status('Esperando familiar…'); } }); signaling.watchDescription(room.sessionId, 'guestTv', 'guest', function (offer) { receiveGuest(offer).catch(diagnostics.error); }, diagnostics.error); signaling.watchEnd(room.sessionId, function (endedBy) { if (endedBy) { if (peer) { peer.close(); } signaling.cleanupSession(room.sessionId, room.code).catch(diagnostics.error); diagnostics.dispose(); diagnostics.status('Llamada terminada.'); } }); } catch (error) { diagnostics.error(error); } }
document.getElementById('end-call').addEventListener('click', async function () { try { if (peer) { peer.close(); } if (room) { await signaling.cleanupSession(room.sessionId, room.code); } diagnostics.dispose(); diagnostics.status('Llamada terminada.'); } catch (error) { diagnostics.error(error); } }); start();
